name: Deploy Site (S3 + CloudFront)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      CF_DISTRIBUTION_ID: ${{ vars.CF_DISTRIBUTION_ID }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.NODE_VERSION || '20' }}

      - name: Build Astro
        working-directory: apps/site
        run: |
          echo "PWD=$(pwd)"
          ls -la
          npm install --no-audit --no-fund
          npm run build

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::134856927288:role/github-oidc-deploy
	  audience: sts.amazonaws.com

      - name: Sync to S3
	  working-directory: apps/site
  	  run: |
    	    aws s3 sync dist "s3://$S3_BUCKET" --delete --cache-control max-age=60

      - name: Invalidate CloudFront (optional)
        if: ${{ env.CF_DISTRIBUTION_ID != '' }}
        run: |
          aws cloudfront create-invalidation --distribution-id "${CF_DISTRIBUTION_ID}" --paths "/*"
